.shared_windows_runners:
  tags:
    - shared-windows
    - windows
    - windows-1809

stages:
  - build

before_script:
 - Set-Variable -Name "time" -Value (date -Format "%H:%m")
 - echo ${time}
 - echo "started by ${GITLAB_USER_NAME}"
 - choco install -y --no-progress patch dos2unix cmake nsis

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Buildtools" --add Microsoft.VisualStudio.Component.VC.ATL --downloadThenInstall --quiet
    - $env:Path += ';C:\Program Files\CMake\bin;C:\Program Files (x86)\NSIS'
    - ./BuildGitlabCI.bat
  artifacts:
    paths:
      - BzTest.exe